news: Receiver

n: 
  repository_dispatch:
    types: [tindie_dispatch]

obs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: tindie_dispatch received
        run: |
          echo "Tindie Notice Received '${{github.event.client_payload.request}}'"

