name: Receiver

on: 
  repository_dispatch:
    types: [tindie_dispatch]

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: tindie_dispatch received
        run: |
          echo "Tindie Dispatch Received '${{github.event.client_payload.request}}'"

